name: ci

on:
  push:
    branches:
      - "main"
  schedule:
    - cron: "*/15 * * * *"

jobs:
  build:
    name: "on ubuntu-latest"

    runs-on: ubuntu-latest

    concurrency:
      group: ci
      cancel-in-progress: true

    permissions:
      contents: write
      actions: write

    steps:
      - uses: actions/checkout@v4

      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/$GITHUB_REPOSITORY/actions/jobs/25147646380/rerun
