name: ci

on:
  push:
    branches:
      - "main"
  schedule:
    - cron: "*/15 * * * *"

jobs:
  build:
    name: "on ubuntu-latest"

    runs-on: ubuntu-latest

    concurrency:
      group: ci
      cancel-in-progress: true

    permissions:
      contents: write
      actions: write

    steps:
      - uses: actions/checkout@v4

      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh run rerun 9176129350 --failed
