name: ci1

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: "PHP 8.2 on ubuntu-latest"

    runs-on: ubuntu-latest

    concurrency:
      group: ci1
      cancel-in-progress: true

    # timeout-minutes: 120

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: git status

      - run: git pull

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          tools: composer

      - run: composer install

      - run: |
          gpg --batch \
            --output database/database.sqlite \
            --passphrase ${{ secrets.GPG_PASSPHRASE_1 }} \
            --cipher-algo ${{ secrets.GPG_CIPHER_ALGO_1 }} \
            --decrypt database/database.sqlite.gpg

      - run: php artisan struct:sensor

      - run: rm database/database.sqlite.gpg

      - run: |
          gpg --batch \
          --output database/database.sqlite.gpg \
          --passphrase ${{ secrets.GPG_PASSPHRASE_1 }} \
          --cipher-algo ${{ secrets.GPG_CIPHER_ALGO_1 }} \
          --symmetric database/database.sqlite

      - run: git status

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "git auto commit"
