name: ci1

on:
  push:
    branches:
      - "main"
      - "perf"

jobs:
  build:
    name: "PHP 8.2 on ubuntu-latest"

    runs-on: ubuntu-latest

    concurrency:
      group: ci1
      cancel-in-progress: true

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: df -h

      - run: git status
      - run: git pull

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          tools: composer

      - run: composer install

      # from LFS
      - run: GIT_CLONE_PROTECTION_ACTIVE=false git clone https://${{ secrets.LFS_REPO_USER }}:${{ secrets.LFS_REPO_PASS }}@${{ secrets.LFS_REPO_HOST }}/${{ secrets.LFS_REPO_NAME }}.git ../lfsrepo

      - run: |
          gpg --batch \
            --output ../lfsrepo/database.sqlite.7z \
            --passphrase ${{ secrets.GPG_PASSPHRASE_1 }} \
            --cipher-algo ${{ secrets.GPG_CIPHER_ALGO_1 }} \
            --decrypt ../lfsrepo/database.sqlite.7z.gpg

      - run: 7z x ../lfsrepo/database.sqlite.7z -odatabase/

#      - run: php artisan struct:sensor --domain=${{ secrets.DOMAIN_20240519_1235 }} --sleep=7
#        env:
#          MINI_APPID_1: ${{ secrets.MINI_APPID_1 }}

      - run: php artisan struct:coding-school --domain=${{ secrets.DOMAIN_20240601_0056 }} --sleep=9 ${{ github.event.head_commit.message }}
        if: ${{ startsWith(github.event.head_commit.message, '--') }}

      - run: |
          rm   ../lfsrepo/database.sqlite.7z
          7z a -mx7 ../lfsrepo/database.sqlite.7z ./database/database.sqlite

      - run: |
          rm ../lfsrepo/database.sqlite.7z.gpg
          gpg --batch \
          --output ../lfsrepo/database.sqlite.7z.gpg \
          --passphrase ${{ secrets.GPG_PASSPHRASE_1 }} \
          --cipher-algo ${{ secrets.GPG_CIPHER_ALGO_1 }} \
          --symmetric ../lfsrepo/database.sqlite.7z

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "git auto commit"

      # to LFS
      - run: git -C "../lfsrepo" config user.name "${{ secrets.LFS_REPO_USER }}"
      - run: git -C "../lfsrepo" config user.email "${{ secrets.LFS_REPO_USER }}@${{ secrets.LFS_REPO_USER }}.com"
      - run: git -C "../lfsrepo" add .
      - run: git -C "../lfsrepo" commit -m "to LFS"
      - run: git -C "../lfsrepo" push

      - run: exit 1

