name: ollama

on:
  push:
    branches:
      - "main"
      - "perf"

jobs:
  build:
    name: "PHP 8.2 on ubuntu-latest"

    runs-on: ubuntu-latest

    container: charescape/web:ubuntu22-php82-mysql80.rv5

    concurrency:
      group: ollama
      cancel-in-progress: true

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: df -h

      # from LFS
      - run: GIT_CLONE_PROTECTION_ACTIVE=false git clone https://${{ secrets.LFS_REPO_USER }}:${{ secrets.LFS_REPO_PASS }}@${{ secrets.LFS_REPO_HOST }}/${{ secrets.LFS_REPO_NAME }}.git ../lfsrepo

      - run: |
          curl -L https://ollama.com/download/ollama-linux-amd64 -o /usr/bin/ollama
          chmod +x /usr/bin/ollama
          /usr/bin/ollama serve &
          sleep 9
          /usr/bin/ollama pull starcoder2:15b
#          /usr/bin/ollama pull codestral:22b
#          /usr/bin/ollama pull deepseek-v2:16b

      - run: |
          mkdir -p ../lfsrepo/ollama
          mv ~/.ollama/* ../lfsrepo/ollama/
#          7z a ../lfsrepo/ollama.7z ~/.ollama/*

      # to LFS
      - run: git -C "../lfsrepo" config user.name "${{ secrets.LFS_REPO_USER }}"
      - run: git -C "../lfsrepo" config user.email "${{ secrets.LFS_REPO_USER }}@${{ secrets.LFS_REPO_USER }}.com"
      - run: git -C "../lfsrepo" add ollama/*
      - run: git -C "../lfsrepo" commit -m "to LFS"
      - run: git -C "../lfsrepo" push

      - run: exit 1
